# ---
env:
    BUILD_DEPENDENCIES: build-essential git golang-go wget
    GOCILINT_VERSION: 1.59.1
# ---
on: [push]
jobs:
    tests:
        runs-on: docker
        container:
            image: debian:latest
        steps:
            - name: Install OS Dependencies
              run: |
                apt-get update && apt-get install --yes $BUILD_DEPENDENCIES
            - name: Install linter
              run: |
                wget -O lint.deb https://github.com/golangci/golangci-lint/releases/download/v$GOCILINT_VERSION/golangci-lint-$GOCILINT_VERSION-linux-amd64.deb
                dpkg -i lint.deb
                rm lint.deb
            - name: Add CI User
              run: |
                useradd -m ci-user
            - name: Clone Repository
              run: |
                mkdir app
                chown ci-user:ci-user app
                su -c "git clone -b ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }} app" ci-user                
            - name: Get deps
              run: |
                cd app
                su -c "go get -u ./..." ci-user
            - name: Build
              run: |
                cd app
                su -c "unshare -c -n make all" ci-user
            - name: Lint
              run: |
                cd app
                su -c "unshare -c -n make lint" ci-user
