on: [push]
jobs:
    tests:
        runs-on: docker
        container:
            # https://codeberg.org/fkooman/frkoci
            image: codeberg.org/fkooman/ci:latest
        steps:
            - name: Clone
              run: |
                git clone --depth 1 -b ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }} .
            - name: Build
              run: |
                unshare -U -n go version
                unshare -U -n make all
            - name: Test
              run: |
                unshare -U -n make test
            - name: Lint
              run: |
                unshare -U -n make lint
